#!/bin/bash

# required
pgrep -x sxhkd 1>/dev/null || sxhkd &
# imports
[ -f "$HOME/.config/polybar/launch.sh" ] && . ~/.config/polybar/launch.sh &
type nm-applet && nm-applet --no-agent &

# global
bspc_config_global() {
    declare -A props=(
        # colours
        ["normal_border_color"]="#9EAAB8"
        ["active_border_color"]="#5C7A92"
        ["focused_border_color"]="#2F506B"
        ["presel_feedback_color"]="#2A2F32"
        # spacing
        ["border_width"]=2
        ["window_gap"]=7
        ["split_ratio"]=0.50
        ["borderless_monocle"]="true"
        ["gapless_monocle"]="true"
        # scheme
        ["automatic_scheme"]="longest_side"
        # pointer
        ["focus_follows_pointer"]="false"
        ["pointer_follows_focus"]="true"
        ["pointer_follows_monitor"]="true"
    )
    for k in "${!props[@]}"; do
        bspc config "$k" "${props[$k]}"
    done
}

# desktop and monitor
bspc_config_monitors() {
    declare -a desktop_names
    declare -a workspaces

    desktop_names=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9")
    # rotate desktop names with monitor count
    for ((monitor_id=1; monitor_id<=$#; ++monitor_id)); do
        workspaces=()
        for ((i=monitor_id-1; i<${#desktop_names[@]}; i+=$#)); do
            workspaces+=("${desktop_names[$i]}")
        done
        bspc monitor "${!monitor_id}" -d "${workspaces[@]}"
    done
}

# exec select configs
bspc_config_monitors "DP-2" "HDMI-0"
bspc_config_global
